### ISSUE TITLE
Add metadata endpoints

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#119]
by @dgarcia360 

> Example with account , repeat for mosaic and namespace.
> GET /account/{accountId}/metadata/
> Returns the complete {accountId} current state metadata. Ideally with pagination + order.
>  
> GET /account/{accountId}/metadata/{key}
> Returns all the {account/namespace/mosaic} current state metadata for that key. The response should be an array, as multiple signers can add metadata with the same key.
> 
> GET /account/{accountId}/metadata/{key}/signer/{publicKey}
> Returns the current state metadata for that {signer, target-id, key}.
> 
> 
> accountId, namespaceId or mosaicId
> where accountId is address or public key
> I changed the endpoints just using "account", so it is easy to follow

as documented in:
https://github.com/nemtech/nem2-openapi/pull/5

**Comment by Vektrat** [comment]
to clarify, assuming the 3 endpoints are developed, there will be a total of  3*3=**9 endpoints**, since each endpoint has the 3 variants depending on type (account, mosaic, namespace)

endpoints must accept both address and public key

**Comment by rg911** [comment]
can the endpoint return all three (account, mosaic, namespace) types in one payload? like what you did in `receipt statement` ?

**Comment by martinayora** [comment]
It will be returned separated. This is how it is being implemented. Following agreement with @Vektrat and @dgarcia360 8 days ago. Although it wouldn't make much sense, because you have to provide an id (account, mosaic  or namespace) to retrieve its own metadata. Otherwise you will be requesting metadata from a key of any entity.

**Comment by rg911** [comment]
would it be better to have one endpoint for `Account/metadata` for all three types using `accountId`, and 3 endpoints for each type (account, mosaic, namespace) querying with its `id`? 
Don't see the point having 9 endpoints here. 

@dgarcia360

**Comment by dgarcia360** [comment]
@rg911 Thanks for reviewing the suggestions! 

``would it be better to have one endpoint for Account/metadata for all three types using accountId`` 

Do you mean something like the following? 

> GET /metadata/{accountId}/
> 
> Returns`` {addressMetadataEntries:[], mosaicsMetadataEntires:[],  namespaceMetadataEntries:[]}`` for that address.

It another possibility, but you would have to query the mosaic/namespace first to get the owner of the corresponding to a given mosaic or namespace. I can't see any additional benefits rather than having fewer endpoints, please list why don't you like the current approach.

Also, I don't see metadata as a single entity that works by its own. Taking into consideration similar features that depend on others (restrictions, multisig), we are creating endpoints under each main independent concept (e.g. ``/account/<:id>/restrictons``, ``/account/<id>/multisig``).

``3 endpoints for each type (account, mosaic, namespace) querying with its id``

Is this already covered with the following endpoints, or would you do something different?

> GET /<account|mosaic|namespace>/{accountId|mosaicId|namespaceId}/metadata/{key}
> Returns all the {account/namespace/mosaic} current state metadata for that key. The response should be an array, as multiple signers can add metadata with the same key.

``Don't see the point having 9 endpoints here.``

The last set of endpoints are optional. We could get the same info with the previous one, but iterating over the array of responses. If you agree that it is not necessary, we could keep these out.

> GET /account/{accountId}/metadata/{key}/signer/{publicKey}
> Returns the current state metadata for that {signer, target-id, key}.

**Comment by rg911** [comment]
Since the PR has been created, I think we just need to adopt it now .

**Comment by Vektrat** [comment]
i think a more appropiate place to discuss the design of the endpoints would be in the openapi issue regarding this, where endpoints have been suggested for _weeks_ now

the REST server offers endpoints, you are not enforced to make use all of them, as Marti said, those were discussed openly, and we adopted the openapi design after public chat where core devs, david, and us, intervened - changes and suggestions are always welcome, but what is on the table right now makes sense, and it is what we agreed would be done for the "deadline" date, we can suggest changes for after this implementation (which we have been working on for days as well) after we see how it goes

**Comment by rg911** [comment]
that's fine, will catch up the OpenAPI issues next time. Thanks for the reply
