### ISSUE TITLE
MetadataTransaction's value in the wrong format

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#150]
Should be hex as described in the open api spec and like the value returned in the metadata endpoints

![image](https://user-images.githubusercontent.com/5390558/66036997-f0935100-e50e-11e9-9d28-0781060823cc.png)

![image](https://user-images.githubusercontent.com/5390558/66037082-21738600-e50f-11e9-9222-5785452fd5ed.png)

I've seen some encoding issues in the listeners/web socket. Once you are returning hex, the encoding problem should be fixed I think.

**Comment by Vektrat** [comment]
this was specifically changed to string (it was binary before), so that it matches the transaction message / messageSize schema ( https://github.com/nemtech/catapult-rest/issues/113 )

should we update the openapi spec format? or convert everything to binary?

i also noticed that for some reason metadata endpoints are inconsistently being returned as binary (hex)

**Comment by dgarcia360** [comment]
Let's divide the decisions we have to make between **transactionsDTOs** and **state DTOs**.

**1. TransactionsDTOs ([AccountMetadataTransactionBodyDTO](https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L2499), [MosaicMetadataTransactionBodyDTO](https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L2536) and [NamespaceMetadataTransactionBodyDTO](https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L2576) value.** 

Problem: Currently, the open-api defines it as a hex-encoded string, but catapult-rest returns a raw string. 

a) **Reasons to keep it as a raw string**
- Better readability (only with the first issued transaction)

b) **Reasons to hex-encode the string**
- Transfer Transaction messages payloads are hex-encoded.
- A xor-ed valued wouldn't be readable anyway after we want to append new metadata to the message.
- Shorter responses

**Action 1**: If possible, I'd go with b), encoding the transaction value as a hex. The outcome is editing catapult-rest formatter to return ``value`` as an hex-encoded string. @Vektrat

**1. [MetadataEntry](https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L3260) value (state).** 

Problem: Apparently none. Right now the value is encoded as a string for better readability (is not a xor-encoded value), and to follow MosaicRestrictions values approach (not hex-encoded either).

However, we could take advantage of this issue to discuss if we want it as well hex-encoded because metadata Transaction value is encoded as hex (although they are different things), or because we want shorter responses.

*Action 2**: Raise a comment if you want to edit how the ``MetadataEntry`` value is formatted. @fboucquez @rg911

**Comment by rg911** [comment]
Agree, hex is probably better. For the state, I would vote for Hex as well. Technically, the SDK can handle both, I'd prefer consistent output here.  

👍

**Comment by Vektrat** [comment]
so everything in hex? metadata value, and transaction message? @dgarcia360 confirm please

**Comment by dgarcia360** [comment]
@Vektrat OK with me if we decide to render metadata transaction/state value as hex.
