### ISSUE TITLE
/account/<accountId>/transactions query parameters not working

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#239]
I've just tried the latest master, it seems like query parameters are not working correctly (transactionType, id) in these endpoints:

https://nemtech.github.io/nem2-openapi/#operation/getAccountConfirmedTransactions
https://nemtech.github.io/nem2-openapi/#operation/getAccountIncomingTransactions
https://nemtech.github.io/nem2-openapi/#operation/getAccountOutgoingTransactions

Examples:

http://localhost:3000/account/10D0BE3CE19B343ED9D96751A355D74B343C3A6877BFAAD626EA6AF72A16EEBC/transactions?transactionType=16724

http://localhost:3000/account/10D0BE3CE19B343ED9D96751A355D74B343C3A6877BFAAD626EA6AF72A16EEBC/transactions?id=5E0A8757A79651568D2FD3F2

![image (3)](https://user-images.githubusercontent.com/5390558/71629670-8b1e3180-2bdd-11ea-9596-f82be32bbb9b.png)

![image (2)](https://user-images.githubusercontent.com/5390558/71629674-92453f80-2bdd-11ea-9281-abb0efc3e421.png)

**Comment by martinayora** [comment]
Regarding page size, remember that you can use any number  provided it is between range specified in config: 
https://github.com/nemtech/catapult-rest/blob/master/rest/resources/rest.json#L30-L31

Transaction type parameter is not working because the param is "type" and not "transactionType". I missed it when approving https://github.com/nemtech/nem2-openapi/pull/59/files#diff-5a80684e299ed8a21bd9404e954ad97bR31.

I used type instead of transacationType as discussed here: https://github.com/nemtech/catapult-rest/issues/166#issuecomment-546428928

We can either update the docs or change the param name on rest. I have no preference. @dgarcia360 , @Vektrat ???

id parameter is used for ordering when using "sortOrder", not for locating specific transactions: https://github.com/nemtech/catapult-rest/blob/master/rest/src/db/CatapultDb.js#L153-L159

**Comment by fboucquez** [comment]
**PageSize:** Just read that the lower limit is 10 so 1 is invalid. Allowing 1 could be nice to do some kind of give me the latest/first giving a query. @dgarcia360 

**Id:** According to the open API, it filters by id and it's independent from the sorting. For orders, you already have the `ordering=id`

**transacationType:** Open API is the source of truth for the SDKs. If we change the spec, we need to change the SDKs. Would it be easier to change the rest?

Is there anything similar to https://www.npmjs.com/package/express-openapi-validator for restify. It would be nice if rest can validate both input and outputs using the open api spec.

**Comment by dgarcia360** [comment]
**PageSize**: As @martinayora has mentioned, this parameter is configurable by catapult-rest instance. The current default value (10)  made sense, as we needed to return the transactions in at least blocks of 10 transactions, but now we could lower this value to 1 by default if there is not any performance issue to not do so.

**transactionType**: Good catch! I agree that the OpenAPI spec should be the source of truth, and actually it would be very beneficial to have a validator. However, in this occasion makes more sense to me to edit the OpenAPI, since when we are using the ``transactionType`` filter, we are always in a ``transaction`` related endpoint, so we could omit the ``transaction`` prefix as we are doing with ``transactionIdLimit``: https://github.com/nemtech/nem2-openapi/blob/master/spec/parameters/transactionIdLimit.yml

Please, accept the PR if you want to change the SDK, or reject it if you prefer to change catapult-rest. https://github.com/nemtech/nem2-openapi/pull/64

**Comment by fboucquez** [comment]
**pageSize:** It's ok if the min is 10. There may be some inconsistency if the min is configurable in rest but hardcoded in the open api spec.  https://nemtech.github.io/nem2-openapi/#operation/getAccountConfirmedTransactions and the [10...100] range

**transactionType:** Fair enough, I'll use type. I'll regenerate the open API libs and update the SDS.

**id:** I thought it would return just the transaction with that given id. But it should return the transactions since including that id. I'll retest.

**Comment by fboucquez** [comment]
Hi @Vektrat,  nothing to fix in your end functionally. 

Would you consider something like https://www.npmjs.com/package/express-openapi-validator?

**Comment by Vektrat** [comment]
> Hi @Vektrat, nothing to fix in your end functionally.
> 
> Would you consider something like https://www.npmjs.com/package/express-openapi-validator?

for now we'd prefer to keep a clean and simple project, we don't see a strong need for this tool atm
