### ISSUE TITLE
Transaction/partial should only return transactions to be cosigned by the account itself

### ISSUE THREAD

**Issue by decentraliser** [nemtech/catapult-rest#244]
[Reference to the discussion in Slack](https://nem2.slack.com/archives/CEZKUE4KB/p1579161981014300)

The `/transactions/partial` endpoint returns aggregate transactions as **notifications** to their recipients:

```
C is multisig account 2-2 of A and B
A initiates a multisig transfer from C to D (classic account)
D transactions/partial ws and REST endpoint will return the partial transaction (Aggregate bonded to be cosigned by B)
```

Although the possibility to be notified of transactions as a recipient seems to be much needed, I propose to do so through a dedicated channel.

The reason is that it should be a common use case to listen to `transactions/partial` events in order to cosign transactions. If so, the **notification** feature comes to complexify such operations, as more logic is needed.

Note that to filter out notification objects from transactions to cosign, you need to:
- _if tx is a multisig account modification_: determine if the account is being added as a cosigner to a new child account, or
- _else:_ determine if the signer of **inner transactions** is a child account

[The open API description seems in line with this opinion:](https://github.com/nemtech/nem2-openapi/blob/99c7bdfaf6fef6d831147e5173df40facd6cea77/spec/core/account/routes/getAccountPartialTransactions.yml#L5)
 Gets an array of aggregate bonded transactions where the account is the sender or requires to cosign the transaction.

**Comment by Vektrat** [comment]
as i mentioned, if this is a relevant enough feature to be added, which i don't see why not, i believe the current endpoint should stay as broad as it currently is (update OpenAPI if misleading)

we can think of adding an extra, more specific, endpoint, that covers just transactions that needs to be cosigned since it seems multiple people has faced this situation before

@dgarcia360 what do you think? and if this is the case, feel free to design the endpoint as well

i considered adding a filter/flag to the `partial` endpoint but i think it will be cleaner to just create a new one

**Comment by decentraliser** [comment]
A filter/flag would sound good to me!

**Comment by decentraliser** [comment]
any news about this one?

**Comment by Vektrat** [comment]
> any news about this one?

i discussed this with david a few weeks ago, precisely the option to add a new endpoint or the filter for this specific case, and this didn't seem to be relevant/necessary enough to add this enhancement, so decision (at that time) was not to proceed with this, though i left the issue open to keep it in mind, and to allow other users that might need it to pile up enough for it to happen

right now there's a similar issue and depending on how it evolves we might come at this again (if not the same, i thought it was the same, they said no, and now we're back here :p)

maybe you want to take another look here @dgarcia360 ? maybe this can fit somehow with the incoming API changes

**Comment by decentraliser** [comment]
what do you refer to by `this enhancement`?

would it be the fact to flag the notification transaction?

I think there's no doubt that the fact to receive a notification among transactions to cosign while having to query a graph to determine if it is indeed a notification or a transaction to cosign is a pain point.

Note that this notification feature was added quite late to REST, and I don't remember it to have been discussed publicly

**Comment by decentraliser** [comment]
Put it like that:

1) The related issue you mentioned (#278) is about being notified when a cosignatory has to sign a transaction. Here there is a required action, so it is very important. However, it is understandable that it is tricky to implement since it involves a max of 25^3 multisig accounts that could be sources of partial transactions for the current testnet config only.

2) Now, consider the relative importance of being notified of a partial transaction that you don't have to sign but of which you are the beneficiary.

Then consider that point 2 messes with point 1...

**Comment by Vektrat** [comment]
i understand, and i usually avoid taking client-based decisions unilaterally because after all i'm not an everyday API user, so i always consult with people that are more in contact with the API (aplications, documentation) - this is why i consulted with @dgarcia360 and brought his attention again - i also thought this request made sense at the beginning, this is why it is still open, i think you make valid points
 
on:
1.  yes... doing so server side would be killer (i don't understand the max. 25 tho? seems a bit overkill as well) - however, we find ourselves in a heavily distributed environment and we try to keep the REST server to minimal and basic functionality so that it does not grow too much with importance - it is a resource like a cache, it should be used when possible and to make things easier, but clients should always do the heavy work and work with trusted/updated data as much as they can, though this is complex at times because it is very comfortable to work with a synchronous REST server

we will consider this once again when david has a chance to review it

**Comment by decentraliser** [comment]
just checked and it's not 25 anymore in the testnet, but I was talking about the max possible number of multisig accounts, which is `maxCosignedAccountsPerAccount ^ maxMultisigDepth`

right on, thanks for considering it! :)

**Comment by dgarcia360** [comment]
@decentraliser I see your point, the issue looks like ``addedAsCosignatory`` (does not exist), and ``partial`` responsibilities are mixed. 

Now REST is going to replace this endpoint with a more complex search endpoint proposal https://github.com/nemtech/symbol-openapi/pull/99.  

* If REST supported the filter requested, the new endpoint would have to filter by ``signerPublicKey``. Note that the proposal tries to make the transaction endpoints only searchable by addresses. 
* ``/transactions`` supports filtering by ``groups`` (e.g. partial), and a group corresponds to a MongoDB collection. To support the filter requested, ``TransactionGroupEnum`` would have to include a new option without the corresponding collection on Mongo, which does not look right.

For these reasons, I would prefer to solve this issue on the SDK layer at this moment. This does not mean that we need to close this issue - the problem still there, although we may apply a patch on the SDK. In fact, if some of you can think of an alternative, do not hesitate to submit a PR on the [OpenAPI Spec](http://github.io/nemtech/symbol-openapi) to discuss the proposed solution on paper.

**Comment by dgarcia360** [comment]
We'll retake this issue on REST now that the search ``/transactions/partial`` endpoint has its own endpoint again https://github.com/nemtech/symbol-openapi/pull/160 I'll submit a new proposal defining how this new filter could look like.

**Comment by dgarcia360** [comment]
@Vektrat After reviewing the issue in-depth, I found it complex to find a solution that perfectly covers every case. Here are my thoughts:

## Problem

An account A receives the partial notification through the WS or ``/transactions/partial?address=<address>`` if the ``meta.addresses`` array contains A address. A could be the aggregate signer, the recipient of some inner transaction, or might need to sign the transaction. 

However, clients might only be interested in receiving the transaction in the latest case (sign the transaction). 

Although the approach suggested by @Decentraliser to add a filter in REST looks possible after the pagination refactor, it is required to define first in what **pending to be signed** means to make sure every case is well covered. Then, consider if REST is the right layer where this logic should be developed.

## Definition: Pending to be signed

To know if the aggregate needs to be signed by the account A, a dev needs to check if the aggregate transaction contains an inner transaction that matches at least one of the following conditions:

_1. Default case_
- A has not cosigned the transaction already.

_2. Pending signature case_ 
- An inner transaction signerPublicKey field matches A's public key.
- A's public key does not match the parent's aggregate signerPublicKey.
     
_3. Cosignatory opt-in case:_ 
- An inner transaction is a MultisigModificationTransaction.
- A's address is present in the inner transaction addressAdditions array.
- A's public key does not match the parent's aggregate signerPublicKey.

_4. Metadata opt-in case:_
- An inner transaction is a Metadata Transaction.
- A's address matches the inner targetAddress.
- A's public key does not match the parent aggregate signerPublicKey.

### Edge cases

- If A is a multisig account, it does not look possible to determine if all required cosignatories from A have not cosigned the transaction already since the number of cosignatories might change over time while the transaction is in the partial state or the account can have multiple levels.
- The cases listed before will fail if A is a 1-of-N multisig account, a cosigner of has signed the parent aggregate, and there are more transactions pending to be signed.
- Please review if I have missed any other case.

## Proposed solution

My recommendation is the same as in https://github.com/nemtech/catapult-rest/issues/244#issuecomment-601410908.  It looks feasible without modifying REST to create a reusable service in the SDK layer that checks if the partial transaction needs to be cosigned or not by a given account. I would start small by completely implementing this logic on the client-side first, trying to solve every edge case, and completing the "pending to be signed" definition, especially for multisig accounts. This would allow reducing risks by testing well every case before migrating the solution to the REST layer since it's very likely that the contract will need to be reviewed several times if this exercise is not done.

Then, you could opt to implement a filter like  ``pendingSignerPublicKey=<signerPublicKey>``* for ``GET /transactions/partial`` and edit the WebSocket (only if REST can cover every case with the information available on MongoDB in a reasonable amount of time). Worst case scenario, the logic will be available in the SDK if moving it to the REST layer is not feasible.

``*`` If you add this filter in the REST layer, it would be preferable to create a new filter like ``pendingSignerPublicKey`` instead of a ``pending`` boolean filter combined with ``signerPublicKey`` because the latest is being used for other purposes. Also, ``pending`` boolean could not be combined with the current ``address`` filter since the public key cannot be derived from the address.

**Comment by Vektrat** [comment]
okay many thanks for the detailed input david, as suggested and given the non-ideality of the rest implementation we will keep this on the client side, if it becomes a hindrance again in the future we can come back to this, or see if core can cooperate somehow
