### ISSUE TITLE
Add type filter to /block/<:height>/transactions

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-rest#249]
The endpoint [getBlockTransactions](https://nemtech.github.io/nem2-openapi/#operation/getBlockTransactions)  does not currently support filtering by transaction type [(example)](https://nemtech.github.io/nem2-openapi/#operation/getAccountConfirmedTransactions).

**Comment by fboucquez** [comment]
I think there are too many different paths returning the same objects. This requires many different rest controllers and many different repository methods in the SDKs and they are hard to combine. One example of multiple endpoints is the transaction ones.

https://nemtech.github.io/nem2-openapi/#operation/getAccountConfirmedTransactions
https://nemtech.github.io/nem2-openapi/#operation/getAccountIncomingTransactions
https://nemtech.github.io/nem2-openapi/#operation/getAccountOutgoingTransactions
https://nemtech.github.io/nem2-openapi/#operation/getAccountUnconfirmedTransactions
https://nemtech.github.io/nem2-openapi/#operation/getAccountPartialTransactions
https://nemtech.github.io/nem2-openapi/#operation/getTransactions
https://nemtech.github.io/nem2-openapi/#operation/getBlockTransactions
https://nemtech.github.io/nem2-openapi/#operation/getTransactions

I believe we can have one central /transaction endpoint that receives a criteria object (via query params or post body)

Example:

http://localhost:3000/transactions
With the following parameter:

- accountId: optional signer
- transactionIds: optional list of transaction ids or hashes
- transactionTypes: optiona list of transaction types
- status: optional list of expected status like [partial, confirmed,unconfirmed]
- transactionDirection: optional incoming, outgoing
- sortBy: optional sorting field like id or -id
- height: optional block height 
- pageSize: optional pageSize default value 25
- pageIndex: optional, default value 0/1 (for first page)

The result should be a Page<Transactions> with:

- values: List<Transactions> (the only generic method, the rest are generic page values) 
- total: the total amount of transaction that apply the criteria (it could 100s)
- pageSize: the current page size (it could be 25 or less if it's the last page)
- pageIndex: like 0/1 if it's the first page.
- lastPage: boolean telling the user if there are more pages (different pageIndex) that needs to be loaded

Then you can combine the different criteria values (AND together) to get the exact transaction you wan get. 

For example, the queries:

http://localhost:3000/transactions?height=1&transactionTypes=16717,16718,16973,17230&signer=neesisAccount&pageIndex=0

http://localhost:3000/transactions?height=1&transactionTypes=16717,16718,16973,17230&signer=neesisAccount&pageIndex=1

Could potentially help me getting the right transactions to create the NetworkCurrency objects in PR https://github.com/nemtech/nem2-sdk-java/pull/214

This is an example, there could many more uses.

This solution can also scale. If we need new filtering, we just add a new optional param to the criteria object instead of creating a new endpoint. 

The same pattern could apply to other queries:
https://nemtech.github.io/nem2-openapi/#operation/getMosaics
https://nemtech.github.io/nem2-openapi/#operation/getMosaicsFromAccount

They could be unified returning the same Page<Mosaic>

**Comment by Vektrat** [comment]
i've not gone through all of this yet, but it's true, i was working on a refactor and i encountered that the incoming/outgoing/etc endpoints are too many, those instead could be a param of some sort, but we haven't changed this to avoid requiring changes on the SDK, if you are fine with changing this we can update it with a better design np

**Comment by fboucquez** [comment]
I'm perfectly fine with having this new unique endpoint. It's actually simpler for us. We create one repository method for each entity and that's it. We don't need to replicate calls.

The only question mark is that the values are AND together which could be a bit restrictive (no more than current implementation). The user may want to OR some params but that gets complicated very fast to the point you end up having a custom query language. (height =1 and (transaction type = Transfer or signer = ABC)).
