### ISSUE TITLE
transaction type filter returns 500 error

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#270]
errored when query using transaction type filter

```
error: caught error 500arrayString.split is not a function {"jse_shortmsg":"arrayString.split is not a function","jse_cause":{},"jse_info":{},"body":{"code":"Internal","message":"arrayString.split is not a function"},"stack":"InternalError: arrayString.split is not a function\n    at Object.toRestError (/app/catapult-rest/rest/_build/server/errors.js:31:5)\n    at toRestError (/app/catapult-rest/rest/_build/server/bootstrapper.js:33:27)\n    at promiseAwareHandler (/app/catapult-rest/rest/_build/server/bootstrapper.js:165:12)\n    at nextTick (/app/catapult-rest/rest/node_modules/restify/lib/chain.js:165:13)\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)","timestamp":"2020-03-01T10:25:45.833Z"}
```

**Comment by Vektrat** [comment]
you should report more details when opening an issue

what is the exact endpoint you're calling? the param name should be `type` and the list comma separated

**Comment by rg911** [comment]
account/transactions, only the account endpoint applied the transaction filter

**Comment by Vektrat** [comment]
you're not trying to filter by type then?

**Comment by rg911** [comment]
error when filters applied

**Comment by martinayora** [comment]
Can you provide an example on how are you calling the endpoint?

This example should be working:
`[host:port]/account/[account_address]/transactions?type=16717,16718,16973`

**Comment by Vektrat** [comment]
can you provide the exact url you are calling?

**Comment by rg911** [comment]
it was working before the openAPI doc changed the filter type from comma-separated string to array. 
https://github.com/nemtech/symbol-openapi/commit/92a0a2a5d11b6fafee73f09f2410b0dd6c50a02c

**Comment by Vektrat** [comment]
i don't know why the change happened, but this endpoint has not changed and we tested it and it is working, i'm also unsure about the openapi spec

https://swagger.io/docs/specification/serialization/

**Comment by dgarcia360** [comment]
The OpenAPI spec looks correct as well:

![image (13)](https://user-images.githubusercontent.com/9107969/75684074-107e9a80-5c90-11ea-9092-f2c22df2a6cc.png)

Executing the query from the swagger editor, it returns a 200 Ok response:

![image (14)](https://user-images.githubusercontent.com/9107969/75684218-3d32b200-5c90-11ea-81f7-07d4ebcf28aa.png)

The problem might be in the OpenApi _Generator for TypeScript_ not supporting queryParams serialization. Let's move the issue to https://github.com/nemtech/symbol-openapi-generator

**Comment by fboucquez** [comment]
Ok. So there are many ways of sending lists of value suing query params:

https://medium.com/raml-api/arrays-in-query-params-33189628fa68

Open API uses the good practice of not hardcoding the CSV to the params. Users may be able to use different notations.

At the moment, the TS generated client uses the format: 

?foo[]=bar&foo[]=qux

![image](https://user-images.githubusercontent.com/5390558/75685371-38aecf00-5c79-11ea-808b-d11bc5c246a3.png)

![image](https://user-images.githubusercontent.com/5390558/75685630-a0fdb080-5c79-11ea-9a1c-f1eed8266111.png)

And actually the rest framework is smart enough to know when the passed parameter is an array.

![image](https://user-images.githubusercontent.com/5390558/75686338-deaf0900-5c7a-11ea-816a-02803687ca91.png)

I suggest @Vektrat and @martinayora to change parseUintArrayString so it knows how to transform the array of string into an array of int too, not only to support CSV strings. 

Java doesn't have the problem because it uses the CSV notation when sending the param.

**Comment by Vektrat** [comment]
I'm against supporting multiple formats at once, it is unnecessary, creates potential confusion and induces to having ugly code in order to expect a variable to have different types (just like it is/was happening with accountIds)

we chose one of the most, if not the most common, way to support lists of params in the API, that is simple comma separated, and we have been using this for a while now, it was also documented, and it is explicitly supported by the openapi spec, i still don't see the problem

the server supports this (in my opinion) ugly format, because there's a specific setting that by default is set to true, but the nature of the API is to accept comma-separated params - i suggest the client adapts to the API, which is not custom at all, and if this is problematic, we should come up with a format that we all agree on (which in this case would be a format that allows one of the clients to act lazy and impose its format on the API, which i'm not happy with)

however, multiple supported formats, from my side, is out of the table

**Comment by fboucquez** [comment]
1) It's open API [recommendation](http://watson-developer-cloud.github.io/api-guidelines/swagger-coding-style.html#parameters)
2) Accepting standards helps user's adoption. We should try to make life easier to devs
3) It's a one/two liner change in rest.
4) If a valid value has a coma, basic CSV won't help you anymore

![image](https://user-images.githubusercontent.com/5390558/75692355-300fc600-5c84-11ea-95d0-40c036cfc19f.png)

**Comment by Vektrat** [comment]
1. ok
2. neither is a standard afaik, and honestly, we are not currently using a super weird custom solution, CSV has been in APIs forever, and probably with more popularity than array of CSV
3. it's not about this
4. true
5. we can't expect to modify the server just because _a_ client, more precisely an automatic code generator, does not support a specific format (and probably has hooks you can customize, if not plugins), now it is the TS generator, in one month maybe a python generator decides it prefers a completely different approach - Java is working, other people supposedly using this endpoint is fine, the OpenApi3 spec supports it, and the OpenApi3 docs support it

i agree with 1) and 4), and i'm fine with changing this to the array of CSV solution, but i'm still against supporting multiple formats in one situation - we have an openapi3 to define how a specific format is, and we have API docs to determine how an endpoint should be, and as you said it is an standard, so i don't see a strong necessity to add multi-format support to parse query params

**Comment by rg911** [comment]
- If it is only couple of lines changes, I don't see why it ` is out of the table` . Plus it is not adding any stress but simply coping different serialization types. In fact this can be an improvement  to cope with different types of qs serialization formats. Ts-sdk chooses typescript-note template from the openAPI. There are also tens of other client templates other users might interested to fit different purposes. 
- The effort to change it on SDK is a lot more than a couple lines. We need to create a custom template off the 'official' openAPI typescript-node one, which we definitely want to avoid. Haven't try other templates yet, but I guess it might hit the same issue. The other option is to change the OpenAPI specification doc to use string (false) type rather than array. Again I don't feel this is the right way to do so neither.

**Comment by Vektrat** [comment]
because how many lines a change takes has never mattered to use when adding features, it's about consistency, and making good, simple code - REST is not here to satisfy a hundred different formats different clients may feel comfortable with at a given time due to third party dependencies

the project is currently implementing a widely supported approach any client can achieve, so i don't see a strong necessity in terms of compatibility to change how things are being done right now - as i said, if someone with a python or swift library opened a similar issue in one month because his template works in a different way, he'd have the same rights to claim changes (which to me have little foundation)

as i said, i'm not saying "no" to the changes, for the reasons fernando stated which are valid and i agree with, array-csv is superior to the current solution because it seems to be more standarized, and because it has wider support (comas in values, which is not a thing right now, but it's a fact)

all i'm saying is supporting multiple formats, when unnecessary, is something we want to avoid, and that it already is being an issue with accountIds in some aspect (with publicKeys and addresses), and right now it may be 2 lines (and it isn't, we have tests), but if at some point we update the framework it may become a pain, and it's a server-side customization that will just offer more trouble than helpfulness (in terms of client confusion as well)

as mentioned as well, doubt there's a way for openapi3 that allows multiple formats at once, this is something that points at a bad practice as well, using conditional parsing randomly always leads up to trouble, we have a spec, it is widely used, and we are sticking to it, anything else is encouraging lazy clients

also, if we upgrade to array-csv, it is because the current implementation is not as good as it could be, so i don't see why would we need to keep both options at once, if one is worse than the other, if they are providing equal functionality, if it's not possible (or painful) to document them, and if one is not so standard

**Comment by fboucquez** [comment]
If you change the method to:

````
const parseUintArrayString = arrayString =>
			routeUtils.parseArgumentAsArray({ param: Array.isArray(arrayString) ? arrayString : arrayString.split(',') }, 'param', 'uint');
````

Rest will support:

http://localhost:3000/account/TB2ZEHASY2FP2FKF7EJOCL6RB3ZXXWZGBXFZYGRW/transactions?type[]=16974&type[]=16718

http://localhost:3000/account/TB2ZEHASY2FP2FKF7EJOCL6RB3ZXXWZGBXFZYGRW/transactions?type=16974&type=16718

http://localhost:3000/account/TB2ZEHASY2FP2FKF7EJOCL6RB3ZXXWZGBXFZYGRW/transactions?type=16974,16718

**Comment by rg911** [comment]
> If you change the method to:
> 
> ```
> const parseUintArrayString = arrayString => routeUtils.parseArgumentAsArray({ param: Array.isArray(arrayString) ? arrayString : arrayString.split(',') }, 'param', 'uint');
> ```
> 
> Rest will support:
> 
> * [http://localhost:3000/account/TB2ZEHASY2FP2FKF7EJOCL6RB3ZXXWZGBXFZYGRW/transactions?type[]=16974&type[]=16718](http://localhost:3000/account/TB2ZEHASY2FP2FKF7EJOCL6RB3ZXXWZGBXFZYGRW/transactions?type%5B%5D=16974&type%5B%5D=16718)
> * http://localhost:3000/account/TB2ZEHASY2FP2FKF7EJOCL6RB3ZXXWZGBXFZYGRW/transactions?type=16974&type=16718
> * http://localhost:3000/account/TB2ZEHASY2FP2FKF7EJOCL6RB3ZXXWZGBXFZYGRW/transactions?type=16974,16718

half a line change on rest will save lots efforts

**Comment by fboucquez** [comment]
Also, all the query params above are part of JSON rest. It's not that we are requesting binary or xml serialization. It's not a really crazy request.

**Comment by Vektrat** [comment]
I keep giving you reasons why I don't think this is a good approach and all you keep posting is how small the change is and code examples

The issue was opened and you were giving points on why the array-CSV solution is superior to comma separated string - I agreed on this, and accepted the new approach as a better option, offering to provide it, but you want to keep both options - the one that is not good enough, and the one that is better, thus having a system that:

- provides different ways to achieve the same, but not the same options are covered (one supports commas, the other does not)
- encourages param dynamic type
- is not possible to document in openapi3 in a consistent way as far as i know

You are trying to automatically generate a "large/complex" API and have encountered something that is not exactly as specified in the openapi, and to me it looks like you want the server to change so that it adapts to client-specific generators, with a solution that is not even universally good

Both solutions are standard (not really, but widely accepted), but that does not mean it is a standard to support both solutions at once, most APIs do not - this API has a clear description on what the format should be in the openapi3, just like most APIs do

This change does not convince me as a necessity, it would aim to support client-dev specific pitfalls, in this case, a specific template of a specific generator, by providing an alternative that is not really an alternative in all the cases

**Comment by Vektrat** [comment]
The current solution is listed as supported in the OpenApi3 following the spec

<img width="479" alt="Screenshot 2020-03-03 at 10 54 23" src="https://user-images.githubusercontent.com/434196/75764050-94429080-5d3d-11ea-890f-6f78fff40809.png">

**Comment by Vektrat** [comment]
Another "solution" would be to specify the param in our openapi as `string` (as it was before), after all we are using a string - after all specificing the style/explode is an openapi thing aimed as a hint for the generators, which are not working - though I'd prefer to use the format presented by fernando (deepObject?) which is what is naturally supported by the REST dependency anyway (we are manually parsing comma separated strings atm)

**Comment by dgarcia360** [comment]
After reading your comments and researching some more info, there is no standard nor recommendation either in [OpenAPI](https://swagger.io/docs/specification/serialization/#query-parameters) nor in [RFC3986](https://tools.ietf.org/html/rfc3986) to work with multiple params, so we need to reach an agreement that works for all of us.

That being said, I understand @Vektrat 's point of view that we might not want to support every possible format out there, for example ``?type[]=16974&type[]=16718`` does not seem to be valid for OpenAPI. But also, that it might be costly to do a PR in the OpenAPI generator to fix this issue before the release.

As the first immediate decision that you seem to agree is that ``?type=16974&type=16718`` is better than ``CSV`` format because it does not accept commas. I would opt to do a test and implement it in a separate branch.

Then, @rg911 @fboucquez you could try if we have the same issue with this new format - at the moment for Java and TypeScript SDK only, not for every generator. I assume that both generators 
will support this option since it's the one provided by default.

**Comment by Vektrat** [comment]
final decision is to switch this format to the one suggested by fernando `?type[]=16974&type[]=16718` as long as supported by openapi, which i think it is (deepObject?)

**Comment by fboucquez** [comment]
Hi @Vektrat @rg911 @dgarcia360 

I've found the way of sending this format:

`http://localhost:3000/account/938EE21A47D399346EE26159C970D39223CEC87A2C40A164D3A580A7CC2E13A2/transactions?type=16724&type=16705&type=17220`

In both java and ts without forking the templates.

Open API spec would need to change the explode =  true

```
 transactionType:
      name: type
      in: query
      description: 'Transaction types to filter by, separated by commas.'
      style: form
      **explode: true**
      schema:
        type: array
        items:
          $ref: '#/components/schemas/TransactionTypeEnum'
```
 So officailly we will be supporting the default strategy for quuery lists:

![image](https://user-images.githubusercontent.com/5390558/76019681-da941d00-5f00-11ea-987a-421f8eca0c37.png)

Rest would need to change the parseUintArrayString method as it will be receiving an array when there are multiple values and a string when there is only one value. No need for CSV split if rest doesn't want to. Rest cannot tell if a single query param is a singleton list or a single value.

Typescript needs to set the` this.accountRoutesApi.useQuerystring = true;` in the Http objects (this changes the low level query serializing implementation)

**Comment by fboucquez** [comment]
The current master fails when there is only one type sent. The rest framework cannot tell if a single query param is a simple string or an array of one.

![image](https://user-images.githubusercontent.com/5390558/76412532-86f75880-6372-11ea-93a2-20908612114b.png)

You will need to add the Array.isArray if statement

**Comment by Vektrat** [comment]
because this format is supposed to be used with `?=type[]=a&type[]=b`

so in the end we have a solution that is ambiguous, and does not support commas and requires a hack at REST side, we will work on this though

**Comment by fboucquez** [comment]
We both approve going with type `form` and` explode=true`

https://github.com/nemtech/symbol-openapi/pull/91

It's not ambiguous, the only official format supported is `?type=16724&type=16705&type=17220`
