### ISSUE TITLE
Rest gateway does not reconnect to the mongodb if it gets restarted.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-rest#271]
If the mongodb restarts, the rest gateway does not reconnect and keeps returning error 500 to the SDK.

error: caught error 500pool destroyed {"jse_shortmsg":"pool destroyed","jse_cause":{"name":"MongoError"},"jse_info":{},"body":{"code":"Internal","message":"pool destroyed"},"stack":"InternalError: pool destroyed\n    at Object.toRestError (/Users/tbdev/code/fork/restgateway/rest/_build/server/errors.js:31:5)\n    at toRestError (/Users/tbdev/code/fork/restgateway/rest/_build/server/bootstrapper.js:33:27)\n    at result.catch.err (/Users/tbdev/code/fork/restgateway/rest/_build/server/bootstrapper.js:162:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","timestamp":"2020-03-05T04:07:30.449Z"}
verbose: connecting to 127.0.0.1:7900 {"timestamp":"2020-03-05T04:08:30.989Z"}
verbose: received data with size 72 {"timestamp":"2020-03-05T04:08:30.992Z"}
verbose: writing response of length: 169 {"timestamp":"2020-03-05T04:08:30.999Z"}
verbose: received data with size 8 {"timestamp":"2020-03-05T04:08:31.002Z"}
verbose: received data with size 64 {"timestamp":"2020-03-05T04:08:31.044Z"}
verbose: client challenge verified? true {"timestamp":"2020-03-05T04:08:31.058Z"}
verbose: received data with size 8 {"timestamp":"2020-03-05T04:08:31.063Z"}
verbose: received data with size 101 {"timestamp":"2020-03-05T04:08:31.104Z"}
error: caught error 500pool destroyed {"jse_shortmsg":"pool destroyed","jse_cause":{"name":"MongoError"},"jse_info":{},"body":{"code":"Internal","message":"pool destroyed"},"stack":"InternalError: pool destroyed\n    at Object.toRestError (/Users/tbdev/code/fork/restgateway/rest/_build/server/errors.js:31:5)\n    at toRestError (/Users/tbdev/code/fork/restgateway/rest/_build/server/bootstrapper.js:33:27)\n    at result.catch.err (/Users/tbdev/code/fork/restgateway/rest/_build/server/bootstrapper.js:162:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","timestamp":"2020-03-05T04:08:31.330Z"}

**Comment by Vektrat** [comment]
right now the initial connection to the database has a `config.maxConnectionAttempts` in it, so that it fails when it cannot connect, and for this reason i think it is/was desirable that does not stay up in a non-functional state (after all, if mongodb does not work most of the functionality is lost)

if the server didn't die, services/orchestrators watching its status would think it is up unless they were smarter by checking the health endpoint (no exit error code would ever happen), so i'm not sure keping the server up when it has lost connection to the database is completely desirable

losing connection to the database is not something that i would expect to randomly happen unless it was because of a problem, or because of operation, and in both cases the devops guy/system would naturally restart all the dependent services anyway, specially REST since it is heavily bound to the database

what do you think about this @kaiyzen ?

**Comment by kaiyzen** [comment]
Think the current retry on startup is good, i look at consistent approach so looking at it like how api node connection is handled where it will try to reconnect.

For instance if node/info fails b/c api is down, and you restart the api node you also dont have to restart rest. We should target to have consistent behavior from mgmt perspective
