### ISSUE TITLE
Cosignatories dont see partial transaction they need to cosign

### ISSUE THREAD

**Issue by evias** [nemtech/catapult-rest#278]
Expected behaviour:

- given a multisig account A, configure to have 2 minApprovals out of 2 cosignatories B and C
- B signs an aggregate bonded transaction containing a transfer issued by A.
- A, B and C should **all** see the partial transactions 

Actual behaviour:

Currently only A and B are able to see the partial transaction when querying /account/A/transactions/partial and /account/B/transactions/partial. 

**C is not able to see to partial transaction even though he is supposed to cosign.**

Environment:

REST v0.7.20

**Comment by Vektrat** [comment]
this happens when C is known by the network? as in, it "fails" for both address and publicKey as `accountId`?

**Comment by evias** [comment]
accountId beibg address,

But both B and C were known by the network

**Comment by dgarcia360** [comment]
In the CLI, we opted to query all the account graph to determine if there are pending transactions to be cosigned or not: https://github.com/nemtech/symbol-cli/blob/master/src/commands/transaction/cosign.ts#L72-L94

I don't think this is an issue but how the feature has worked until now. If we look to the behavior from another point of view, the multisig is the account that should reach the minApproval, C should not cosign necessary the transaction.

This is more clear if we think of a 2-of-3 multisig after adding a new participant D. Now, C is not required to cosign the transaction since it could be accepted just with A and D cosignatures. 

You can see another problematic scenario with the solution proposed when a multisig cosignatory is replaced for a new one while there is an active aggregate bonded transaction. The new multisig cosigner won't be notified apparently, although we decide to notify B.

@Vektrat @martinayora Are transaction ``meta.addresses`` values provided by MongoDB, or do you compute them at the REST layer? 

If it is the first case, it will be very expensive for REST to add all the possible cosigners taking into account that there could be multi-level multisig, and opinionated because REST would be altering the server response.

**Comment by martinayora** [comment]
_meta.addresses_ is read directly from mongoDB. Rest doesn't modify it.

**Comment by Wayonb** [comment]
Its great that the CLI have already fix this problem.  I think this fix needs to be in either rest or sdk so that every client don't need to duplicate the same code.  

I think there is some confusion of what the the fix should be.  The fix is not to change the meta.address vaules.  This is created by the server.  The fix should be similar to the CLI code, i.e. given an address or publickey, get all the transactions in the pt cache that it needs to sign.  I am not sure how expensive this will be but at least this should be a service in the SDK.

From the examples above, I dont think you can assume that an cosigner might not be required to sign.  One cosigner might not be able to access their wallet for a period of time.  

I am not sure I understand the point of the 2-of-3 multisig example.  In this case D would not get notify either to sign transaction since address is not in the meta.address list.  Let me know if I am missed something.

**Comment by evias** [comment]
What I think is a problem though is that it seems `meta.addresses` holds one address that has nothing to do with my multi-signature .. why does this account get notified?

```
{
    "_id" : ObjectId("5e6a4c14aee0a53a70321b6f"),
    "meta" : {
        "height" : NumberLong(0),
        "hash" : { "$binary" : "lN7+ZFm/Qh/b1m2qTFIagB2sOx8tcqe6iu7142I0ZGo=", "$type" : "00" },
        "...
        "index" : 0,
        "addresses" : [ 
            { "$binary" : "mNQ3g36ZO7C7XCj4oHnPM6kiVdTbV3DYqw==", "$type" : "00" }, // TDKDPA36TE53BO24FD4KA6OPGOUSEVOU3NLXBWFL - ???
            { "$binary" : "mCydM+EyrGC91DD60aj4GOH3QHrx0sZCWg==", "$type" : "00" }, // TAWJ2M7BGKWGBPOUGD5NDKHYDDQ7OQD26HJMMQS2 - cosig one
            { "$binary" : "mPr4LKQHR0YkE4MM/ukq09PrRnlJsi1ohg==", "$type" : "00" }  // TD5PQLFEA5DUMJATQMGP52JK2PJ6WRTZJGZC22EG - multisig
        ]
    },
    "transaction" : {
        ...
        "network" : 152,
        "type" : 16961, // aggregate bonded
        ...
        "transactionsHash" : { "$binary" : "xdnFsYfTsAjT+fMBLmbLKuzeNSTGAnOerExfyq54MSo=", "$type" : "00" },
        "cosignatures" : []
    }
}
```

The `TDKDPA36TE53BO24FD4KA6OPGOUSEVOU3NLXBWFL` address does not appear on my multisig config:

- multisig: `TD5PQLFEA5DUMJATQMGP52JK2PJ6WRTZJGZC22EG`
- cosig1: `TAWJ2M7BGKWGBPOUGD5NDKHYDDQ7OQD26HJMMQS2`
- cosig2: `TAD5BAHLOIXCRRB6GU2H72HPXMBBVAEUQRYPHB6C`

That's the multisig info (2 minApproval): http://api-01.us-west-1.symboldev.network:3000/account/D5BEA90017E9EAF48754F33729D635605B14F9FA71E8A99E24461DB7CCFEF5DD/multisig

**Comment by dgarcia360** [comment]
@evias Is it the account receiving the transfer transaction? This issue is being discussed here https://github.com/nemtech/catapult-rest/issues/244

**Comment by evias** [comment]
hey I answered through mail .. didnt work xD 

@dgarcia360, no. The recipient is `evias` namespace, which maps to `cosig1` address

**Comment by Wayonb** [comment]
@evias address TDKDPA36TE53BO24FD4KA6OPGOUSEVOU3NLXBWFL is a valid account.  Can you point me to the full transaction(including inner transaction)?  If the address is on present in any of those transaction then there might be an issue on the server.

http://api-01.us-west-1.symboldev.network:3000/account/TDKDPA36TE53BO24FD4KA6OPGOUSEVOU3NLXBWFL

**Comment by martinayora** [comment]
@Wayonb

**Comment by evias** [comment]
@Wayonb looking at the account, it could be one of the harvesters account that have been setup ... will confirm

**Comment by evias** [comment]
didnt seem to be one of our pre-configured harvesters ..

**Comment by Wayonb** [comment]
@evias I was able to repro and the third is the mosaic Rental Fee Sink account.  I am checking to see if the address should be there.

**Comment by Vektrat** [comment]
@Wayonb i suppose this has already sunken into forgetfulness, but by any chance do you recall how this ended? 😅

**Comment by rg911** [comment]
This has been fixed
