### ISSUE TITLE
Better error message for when the mongodb is down.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-rest#281]
When the mongodb is unavailable or down, rest returns a cryptic message.  The error message needs to be user friendly.

{"code":"Internal","message":"pool destroyed"}

**Comment by Vektrat** [comment]
a 500 error does not need to be user friendly, it is an un expected server error, i believe it is being too friendly already giving information that the user (client) should not care about

i believe the error here should be 503 though, right now it is like so because it is automatically being treated by the framework

**Comment by Vektrat** [comment]
closing because this forms part of a bigger task that was already due, this subtask will be pending on the referenced issue
