### ISSUE TITLE
Getting errors in the symbol server logs when any of the node api calls(node/info, node/time)

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catapult-rest#303]
It looks like for the node/info calls the connection to the server is not close by rest.

2020-04-20 23:07:42.512901 0x00007f672f7fe700: <info> (extensions::NetworkUtils.cpp@124) accept result to local node port 7900 from 127.0.0.1: Accepted 
2020-04-20 23:07:42.514285 0x00007f672d7fa700: <error> (ionet::PacketSocket.cpp@42) failed when reading from socket: stream truncated 
2020-04-20 23:07:42.514389 0x00007f672d7fa700: <warning> (net::ChainedSocketReader.cpp@70) 99EC051441639CC56906AF7C58D90D42A3CD75BC296A29D8F957118FB7F34E97 @ 127.0.0.1 read completed with error: Read_Error 
2020-04-20 23:07:42.514480 0x00007f672d7fa700: <debug> (net::PacketReaders.cpp@139) closing connection to 99EC051441639CC56906AF7C58D90D42A3CD75BC296A29D8F957118FB7F34E97 @ 127.0.0.1 - 0

**Comment by Vektrat** [comment]
a few questions, to understand this further and to know how critical this issue is:
- do you know if this was happening before TLS?
- is this affecting exchange of data? or is it happening during the shutdown stage? this impacts the criticality of the issue
- is it possible those are errors produced by the client abruptly closing the connection rather than negotiating the shutdown?

**Comment by Wayonb** [comment]
1. I did a test with 9.3.1 last week and did not see the error.  The problem of not closing the connection might have always been in rest gateway but is now affecting TLS
https://stackoverflow.com/questions/25587403/boost-asio-ssl-async-shutdown-always-finishes-with-an-error
2. No, the exchange of data is fine.
3. Yes, this is what I am saying..Rest is not closing the connection at the end of the data exchange.  I dont see where Rest is closing the connection to the server.

**Comment by Vektrat** [comment]
>     1. I did a test with 9.3.1 last week and did not see the error.  The problem of not closing the connection might have always been in rest gateway but is now affecting TLS
>        https://stackoverflow.com/questions/25587403/boost-asio-ssl-async-shutdown-always-finishes-with-an-error
> 
>     2. No, the exchange of data is fine.
> 
>     3. Yes, this is what I am saying..Rest is not closing the connection at the end of the data exchange.  I dont see where Rest is closing the connection to the server.

non elegant implementations become more evident when TLS and SSL are around, because those are more strict when treating errors (since they could be exploited as vulnerabilities), this could be the reason why this is becoming more apparent now

if the exchange of data is fine, we will treat this with low prio, because it looks like the kind of issue that takes a major effort to track down

REST is apparently closing the connection here https://github.com/nemtech/catapult-rest/blob/7d242f4247fa1ebe281a1f38d484cb00b64f823e/rest/src/connection/catapultConnection.js#L71 , though I'm not sure if this is as graceful as it could be (not sure if it's waiting for shutdown, etc. or if it's an abrupt close)

we will leave this issue open to check it out when we have less pressing matters than we do now ^^

**Comment by Vektrat** [comment]
ok we will update it with end, thanks for looking into it ^^
