### ISSUE TITLE
multisig graph endpoint returns 500 error

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#363]

**Comment by Vektrat** [comment]
can you put which query were you making? would like to know if you were requesting by publickeys or by addresses to confirm something

@martinayora 
besides that we will have to change this endpoint (and the multisig one) so that publicKeys are no longer accepted:

- **at routes:** multisigPublicKeys => multisigAddresses
- **at routes:** cosignatoryPublicKeys => cosignatoryAddresses

- **at db:** multisigsByAccounts => multisigsByAddresses
