### ISSUE TITLE
transactions/{transactionid} does not return partial transactions

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#372]
using search to get partial transactions and use the hash to call tranasctions/{hash} returns nothing.

**Comment by Vektrat** [comment]
not sure if i understand the issue... will also comment regarding slack message

- to get partial transactions you need to put a filter: `group`, otherwise it defaults to confirmed
- `/transactions/{hash}` is not a defined endpoint, you must use `id`
- i just tried to fetch an aggregate bonded transaction (type `0x4241`) by `id`, and it worked just fine

**Comment by Vektrat** [comment]
i see now what you might mean, getting a partial transaction detail, will check it out

**Comment by Vektrat** [comment]
i think i see what you mean now, i believe this was overlooked by the api review, will discuss with @dgarcia360

**Comment by Vektrat** [comment]
docs: https://github.com/nemtech/symbol-openapi/pull/160
