### ISSUE TITLE
Need API for mosaic balance(s) for specific account at specific historical block. 

### ISSUE THREAD

**Issue by jabo38** [nemtech/catapult-rest#432]
This is not for XYM, but for any and all mosaics. 

It would be really nice to know what a specific accounts specific mosaic balance at a specific block. 

I think the use cases include security tokens, voting, NFA's (Apostille), taxes, and historical audits. 

It really a pretty straight forward API that is just "what is Jeff’s balance of luxtag.coin on block 1000?”

Or could be "what is Jeff's balance for all mosaics at block 1000?" would of course work too and maybe is better.

**Comment by Vektrat** [comment]
this being exclusively for XYM or not would not be an issue since from a tehcnical point of view, XYM is just one more mosaic in the chain

however, as things are now it is technically infeasible without a strong collaboration from the database/core side, which would involve adding a lot of redundant data to the system

as things are now, the REST server would have the same work as a client, with the only advantage of being closer to the database (response time), other than that, it would require heavy execution to calculate for each case and every time the balances - by fetching all relevant transfer data for a specific account/mosaic, all related receipts, and putting it all together to get the supposed end number (and hope it is the same as the balance without us having missed anything)

it is the same case as with a bank extract, usually they have the resulting balance after each operation, we lack this information, and going back over ALL of the historical and related data to manually count it is a technical wall (because in a bank extract it is easier because everything is in the same place and already for a single account, but our case is way more complex)

for this we would require for core to provide with some form of balance snapshots, one possibility that come to mind without giving it much thought would be the addition of another receipt type that reflected the resulting balance for an account after each operation, however, this would grow fast, and it would add a lot of noise because it'd not just be transfer transactions that would modify the balance, but also any kind of fee/tax assumed by interacting in the network

it's not that it would take us long to do so or that we don't think it is worth it, it is that right now, without extra actions at core side that potentially have bigger consequences (skyrocketing storage issues among others), it is not technically possible to do so - and i'm not sure if this issue is important or relevant enough to make the core system go through this change
