### ISSUE TITLE
Incorrect ReceiptType

### ISSUE THREAD

**Issue by Pow1404** [nemtech/catapult-rest#446]
**Description:** The ReceiptType defined in catapult-rest contains a duplicate value which is inconsistent with ReceiptType defined in catapult-server .
 const ReceiptType =    { 
          1 :    'receipts.balanceTransfer' ,
          2 :    'receipts.balanceChange' , 
          3 :    'receipts.balanceChange' ,
          4 :    'receipts.artifactExpiry' , 
          5 :    'receipts.inflation' 
}; 
ReceiptType in catapult-rest ( catapult-rest/catapult-sdk/src/plugins/receipts.js#L24-L30 ). 
///   Enumeration   of   basic   receipt   types.
 ///   \note   BasicReceiptType   is   used   as   highest   nibble   of   receipt   type. enum  class BasicReceiptType   :    uint8_t   {
 ///   Some   other   receipt   type. Other   =    0x0 , 
///   Balance   transfer. BalanceTransfer   =    0x1 , 
///   Balance   credit. BalanceCredit   =    0x2 ,
 ///   Balance   debit. BalanceDebit   =    0x3 , 
///   Artifact   expiry   receipt. ArtifactExpiry   =    0x4 ,
 ///   Inflation. Inflation   =    0x5 , 
///   Aggregate   receipt. Aggregate   =    0xE ,
 ///   Alias   resolution. AliasResolution   =    0xF
 }; 
ReceiptType in catapult-server ( catapult-server/src/catapult/model/ReceiptType.h#L29-L55 ). 
Recommendation: Short term, fix the duplicate ReceiptType value in catapult-rest code base.

**Comment by Vektrat** [comment]
this is extremely easy to address (the recommendation), so we can add it if required

however, the duplicate value is expected and added in purpose:
- flagged types 2 and 3 relate to `BalanceCredit` and `BalanceDebit` respectively, both of those types can be considered a conceptual grouped super-type called `BalanceChange`, which is what we are going for in REST

we could have made two different schemas, yes, but we took this decision because actually, in core (mongoDB schema definition), they are following the same approach, so we are actually being consistent with core and possibly this is what arises confusion

you can check mongodb references in core, or, for easier readability, the catbuffer analogous situation https://github.com/nemtech/catbuffer/blob/main/schemas/receipts.cats#L80 where we can clearly see that BalanceCredit and BalanceDebit are nonexistent as well, but we have `BalanceChangeReceipt` in their place

**Comment by rg911** [comment]
`BalanceChange` is not the actual `ReceiptType`. It defines the  shared receipt schema but should not to be used as the actual type.

**Comment by Vektrat** [comment]
`balanceChange` is the name of the schema in the implementation, nothing to do with documentation or type naming here

**Comment by Pow1404** [comment]
Comment from our external partner following your response Roger. 

_I think this makes total sense (to leave it as it is) but it would be nice to document it in the code as well, via, e.g., a comment_

Can you action the commenting in code?

Thanks

**Comment by Vektrat** [comment]
i believe it is redundant and that it has nothing to do with security, but sure, will add the comment
