### ISSUE TITLE
Performance issue for paginated endpoints

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/catapult-rest#464]
Example : http://api-01.us-east-1.096x.symboldev.network:3000/transactions/confirmed?type=&pageSize=25&pageNumber=1&order=desc

![image](https://user-images.githubusercontent.com/5649156/91633425-bed68300-ea1a-11ea-8985-97126390d530.png)

**Comment by Vektrat** [comment]
thanks, we are aware of this issue and already have an open PR, we expect to merge by the beginning of next week!

https://github.com/nemtech/catapult-rest/pull/463

**Comment by Vektrat** [comment]
i've just recently found out that mongodb's `count()` is a cursor shortcut rather than a database operation, which means that regardless of how the query is done, it will have to scan through the whole result set to return a count value

this means that the performance will always be bad, and get worse as the database grows larger, sadly at this point i haven't found any solution to this and it means that we will most likely be needing to drop the count-dependent pagination features from the API, this basically means that this:

```
  "pagination": {
    "pageNumber": 1,
    "pageSize": 20,
    "totalEntries": 4105273,
    "totalPages": 205264
  }
```

will become this:
```
  "pagination": {
    "pageNumber": 1,
    "pageSize": 20,
  }
```

i know this is an annoyance client side in order to have enhanced pagination, you will still be able to paginate, but you won't know the total number of results or pages (which means displaying the typical pagination navigator on the bottom won't be possible, at least strictly, since you could still show it, but at some point it'd start returning empty results, and you wouldn't be able to know in advance which is the latest page)

the impact of this is something that cannot be easily overlooked (requests that should be almost instant take various seconds to complete, and will grow worse), so we see ourselves kind of forced to take back this feature

i will present this to the team, but sadly i think there's not much room for discussion

@evias @AnthonyLaw

**Comment by AnthonyLaw** [comment]
@Vektrat Hi there, in early explorer we are using `1/...` to indicate the page status.

so without `totalPages`, we can just replace `...` into explorer.

**Comment by rg911** [comment]
What does the query plan look like? Does downfall count (after find etc..) results in better execution plan?

**Comment by fboucquez** [comment]
I understand the problem. If the performance is really bad, let's remove the total fields. Is there a way to at least have "isLastPage" flag? What's pageSize, the requested page size or the size of the data array?

**Comment by Vektrat** [comment]
`pageSize` is the size of the page that is being used (in theory it should be the requested, unless it conflicts with the min/max from settings, it's informative and not of much user to the clients

i'd vote against, `isLastPage`, it's not possible to have this unless we do an extra request to fetch the +1 page from the database for every page that is requested to check it (there's no way to check with the main request), which means we would _always_ need to do this, and it'd not help much anyway, whilst on the other hand the client can just keep on fetching results until there are no more

**Comment by fboucquez** [comment]
ok, all good. We do a isLastPage =  pageSize > data.lenght in the SDKs. In case the last page is the same size of the requested page size, the SDK (or the clients) would need to do an extra call that returns empty.

**Comment by Vektrat** [comment]
> ok, all good. We do a isLastPage = pageSize > data.lenght in the SDKs. In case the last page is the same size of the requested page size, the SDK (or the clients) would need to do an extra call that returns empty.

exactly ^^
