### ISSUE TITLE
/lock/secret/:secret rejects HASH_160 secrets

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#472]
After creating a SecretLockTransaction with a HASH_160, the /lock/secret/:secret endpoint fails. It assumes the `secret` must be 32 bytes, but in this case, it is 20 bytes 
https://github.com/nemtech/catapult-rest/blob/main/rest/src/plugins/lockSecret/lockSecretRoutes.js#L34

**Comment by Vektrat** [comment]
isn't the secret always 32 bytes? 

docs dictate different types of algorithm, but the hash is always 256
https://docs.symbolplatform.com/serialization/lock_secret.html#secretlocktransaction

catbuffer also shows a hash256 type always, regardless of the algorithm of choice
https://github.com/nemtech/catbuffer/blob/main/schemas/lock_secret/secret_lock.cats

do you have any example of this in the testnet we can check?

**Comment by fboucquez** [comment]
Both transaction's secret and info's secret  are filled with 0s

![image](https://user-images.githubusercontent.com/5390558/92406023-5ae44680-f10d-11ea-9672-dc8ed78dec07.png)

![image](https://user-images.githubusercontent.com/5390558/92406028-5e77cd80-f10d-11ea-9109-e65a4f4e2c5b.png)

I'll patch on my side.

**Comment by fboucquez** [comment]
Maybe rest can also accept 20 bytes hashes in this case? Non sdk users may have the same issue.

**Comment by Vektrat** [comment]
> Maybe rest can also accept 20 bytes hashes in this case? Non sdk users may have the same issue.

i don't think this is a good idea, because it would lack consistency:
- when announcing lock transactions, are 20 bytes used, or 32? i believe 32 since catbuffer shows 32
- in the database 32 is always stored, which means this is what the api displays, we'd need to format the hash depending on the algorithm of choice at rest side
- the original format is probably also required to be considered when serializing transactions

another problem for accepting other-sized hashes at REST side is that we need to detect which size it originally is (trivial), and then pad the provided data with (in this case trailing 0s) in order to query the database, but we would be including a strong dependency towards core/database which cannot be automatically managed in any way, in case core made any updates to this

**Comment by fboucquez** [comment]
Fair enough. Closing it
