### ISSUE TITLE
Add mosaic restriction REST endpoints

### ISSUE THREAD

**Issue by Vektrat** [nemtech/catapult-rest#74]
Blocked by and based on: https://github.com/nemtech/nem2-openapi/issues/6

**Comment by dgarcia360** [comment]
@roger  @martin An initial list of endpoints we could have to interact with [Mosaic Restrictions](http://nemtech.github.io/concepts/mosaic-restrictions.html). Could you make a PR with the final specification? Also, review the endpoints structure and list any missing additional endpoint do you think should we have.

**GlobalMosaicRestriction endpoints**

1. **GET** ``/mosaic/{mosaicId}/restrictions``

Returns an array of global mosaic restrictions assigned to the mosaic. Ideally paginated and orderable by key and type.

**AddressMosaicRestriction endpoints**

I propose to organize address mosaic restrictions under mosaics rather than accounts to avoid conflicts with account restrictions endpoints. AccountId stands for address or publicKey. If only address is possible, replace ``account/{accountId}/`` for ``../address/{address}``.

2. **GET** ``/mosaic/{mosaicId}/restrictions/account/{accountId}/``

Returns array of address mosaic restrictions for the given a ``mosaicId`` and ``targetAddress``. Ideally paginated and orderable by key.

Extra: We could have as well POST methods (/mosaic/restrictions and /mosaic/{mosaicId}/restrictions) to get different responses the same call, as we are doing with account restrictions.
